name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        script: |
          echo API_PORT=${{ secrets.API_PORT }} > .env
          echo DOMAIN_URL=${{ secrets.DOMAIN_URL }} >> .env

    - name: build
      run: make build

  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update
      run: make update
