name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v3

    - name: env
      run: touch docker-deploy/.env

    - name: build
      run: make build

  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update
      run: make update
