name: Makefile CI

on:
  pull_request:
    branches: ['*']

env:
  API_PORT: 0
  DOMAIN_URL: ${{ vars.DEPLOY_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: env
        run: touch docker-deploy/.env

      - name: build
        run: make build

      - name: test
        run: npm run test
